/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (AutoCAD Drawings) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/

SELECT COUNT(C_ID) AS ACAD_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS ACAD_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT DOC_VERSION) AS ACAD_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT SHEET_NO) AS ACAD_SHEET_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT TNBL) AS ACAD_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS ACAD_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS ACAD_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT FREE_NAME) AS ACAD_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS ACAD_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT DOC_TYPE) AS ACAD_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_TYPE) AS ACAD_CAX_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT DOC_SUBTYPE) AS ACAD_DOC_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PMT_REF_NO) AS ACAD_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PLANT_ID) AS ACAD_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT LOC_ID) AS ACAD_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS ACAD_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT LEV_IND) AS ACAD_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS ACAD_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT FORMAT) AS ACAD_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_OPBH_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.opbh IS NULL;

SELECT COUNT(C_ID) AS ACAD_OPBH_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.opbh IS NOT NULL;

SELECT COUNT (DISTINCT OPBH) AS ACAD_OPBH_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_SCALE_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.scale IS NULL;

SELECT COUNT(C_ID) AS ACAD_SCALE_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.scale IS NOT NULL;

SELECT COUNT (DISTINCT SCALE) AS ACAD_SCALE_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CAX_COMP_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_COMP_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_COMP_MAP) AS ACAD_CAX_COMP_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_STEP_DESCR_NULL_CNT
FROM T_DOC_DAT
WHERE STEP_DESCR IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_STEP_DESCR_FILL_CNT
FROM T_DOC_DAT
WHERE STEP_DESCR IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT STEP_DESCR) AS ACAD_STEP_DESCR_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SCALE_TXT_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.scale_txt IS NULL;

SELECT COUNT(C_ID) AS ACAD_SCALE_TXT_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.scale_txt IS NOT NULL;

SELECT COUNT (DISTINCT SCALE_TXT) AS ACAD_SCALE_TXT_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_FRAME_ID_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FRAME_ID_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_FRAME_ID) AS ACAD_CAX_FRAME_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_STD_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_STD_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_STD_MAP) AS ACAD_CAX_STD_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_01_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_01_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_01) AS ACAD_CAX_01_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_EDB_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_EDB_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT EDB_URL) AS ACAD_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_SYS_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_SYS_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS ACAD_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT VAL_FROM) AS ACAD_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT (DISTINCT VAL_UNTIL) AS ACAD_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'ACAD';

--- ACAD TYPE FIELDS ---

SELECT COUNT(C_ID) AS ACAD_POS_X_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.POS_X IS NULL;

SELECT COUNT(C_ID) AS ACAD_POS_X_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.POS_X IS NOT NULL;

SELECT COUNT (DISTINCT POS_X) AS ACAD_POS_X_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_POS_Y_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.POS_Y IS NULL;

SELECT COUNT(C_ID) AS ACAD_POS_Y_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.POS_Y IS NOT NULL;

SELECT COUNT (DISTINCT POS_Y) AS ACAD_POS_Y_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_LAY_ID_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.LAY_ID IS NULL;

SELECT COUNT(C_ID) AS ACAD_LAY_ID_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.LAY_ID IS NOT NULL;

SELECT COUNT (DISTINCT LAY_ID) AS ACAD_LAY_ID_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_VIEW_ID_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.VIEW_ID IS NULL;

SELECT COUNT(C_ID) AS ACAD_VIEW_ID_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.VIEW_ID IS NOT NULL;

SELECT COUNT (DISTINCT VIEW_ID) AS ACAD_VIEW_ID_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_LINE_TYPE_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.LINE_TYPE IS NULL ;

SELECT COUNT(C_ID) AS ACAD_LINE_TYPE_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.LINE_TYPE IS NOT NULL;

SELECT COUNT (DISTINCT LINE_TYPE) AS ACAD_LINE_TYPE_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CUSTOMER_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CUSTOMER IS NULL;

SELECT COUNT(C_ID) AS ACAD_CUSTOMER_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CUSTOMER IS NOT NULL;

SELECT COUNT (DISTINCT CUSTOMER) AS ACAD_CUSTOMER_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_COUNTRY_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.COUNTRY IS NULL;

SELECT COUNT(C_ID) AS ACAD_COUNTRY_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.COUNTRY IS NOT NULL;

SELECT COUNT (DISTINCT COUNTRY) AS ACAD_COUNTRY_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_ORDERNR_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.ORDERNR IS NULL;

SELECT COUNT(C_ID) AS ACAD_ORDERNR_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.ORDERNR IS NOT NULL;

SELECT COUNT (DISTINCT ORDERNR) AS ACAD_ORDERNR_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CUSTOMNR_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CUSTOMNR IS NULL;

SELECT COUNT(C_ID) AS ACAD_CUSTOMNR_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CUSTOMNR IS NOT NULL;

SELECT COUNT (DISTINCT CUSTOMNR) AS ACAD_CUSTOMNR_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_PROD_TYPE_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PROD_TYPE IS NULL;

SELECT COUNT(C_ID) AS ACAD_PROD_TYPE_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PROD_TYPE IS NOT NULL;

SELECT COUNT (DISTINCT PROD_TYPE) AS ACAD_PROD_TYPE_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CAP1_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAP1 IS NULL;

SELECT COUNT(C_ID) AS ACAD_CAP1_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAP1 IS NOT NULL;

SELECT COUNT (DISTINCT CAP1) AS ACAD_CAP1_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_TENSION_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.TENSION IS NULL;

SELECT COUNT(C_ID) AS ACAD_TENSION_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.TENSION IS NOT NULL;

SELECT COUNT (DISTINCT TENSION) AS ACAD_TENSION_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_PMT_LANG_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PMT_LANG IS NULL;

SELECT COUNT(C_ID) AS ACAD_PMT_LANG_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PMT_LANG IS NOT NULL;

SELECT COUNT (DISTINCT PMT_LANG) AS ACAD_PMT_LANG_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CAD_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAD IS NULL;

SELECT COUNT(C_ID) AS ACAD_CAD_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAD IS NOT NULL;

SELECT COUNT (DISTINCT CAD) AS ACAD_CAD_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_REMARK_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.REMARK IS NULL;

SELECT COUNT(C_ID) AS ACAD_REMARK_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.REMARK IS NOT NULL;

SELECT COUNT (DISTINCT REMARK) AS ACAD_REMARK_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_MCODE_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.MACH_CODE IS NULL;

SELECT COUNT(C_ID) AS ACAD_MCODE_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.MACH_CODE IS NOT NULL;

SELECT COUNT (DISTINCT MACH_CODE) AS ACAD_MACH_CODE_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_MVERSION_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.MACH_VERSION IS NULL;

SELECT COUNT(C_ID) AS ACAD_MVERSION_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.MACH_VERSION IS NOT NULL;

SELECT COUNT (DISTINCT MACH_VERSION) AS ACAD_MVERSION_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_SPCL_CHAR_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.SPECIAL_CHAR IS NULL;

SELECT COUNT(C_ID) AS ACAD_SPCL_CHAR_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.SPECIAL_CHAR IS NOT NULL;

SELECT COUNT (DISTINCT SPECIAL_CHAR) AS ACAD_SPECIAL_CHAR_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_PROD_TYPE2_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PROD_TYPE2 IS NULL;

SELECT COUNT(C_ID) AS ACAD_PROD_TYPE2_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.PROD_TYPE2 IS NOT NULL;

SELECT COUNT (DISTINCT PROD_TYPE2) AS ACAD_PROD_TYPE2_CARD
FROM T_DOC_ACAD;

SELECT COUNT(C_ID) AS ACAD_CAP2_NULL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAP2 IS NULL;

SELECT COUNT(C_ID) AS ACAD_CAP2_FILL_CNT
FROM T_DOC_ACAD
WHERE 
t_doc_acad.CAP2 IS NOT NULL;

SELECT COUNT (DISTINCT CAP2) AS ACAD_CAP2_CARD
FROM T_DOC_ACAD;