/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (Inventor Drawings) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS INVDRW_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS INVDRW_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT DOC_VERSION) AS INVDRW_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT SHEET_NO) AS INVDRW_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT TNBL) AS INVDRW_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS INVDRW_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS INVDRW_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT FREE_NAME) AS INVDRW_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS INVDRW_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT DOC_TYPE) AS INVDRW_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_TYPE) AS INVDRW_CAX_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT DOC_SUBTYPE) AS INVDRW_DOC_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PMT_REF_NO) AS INVDRW_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PLANT_ID) AS INVDRW_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT LOC_ID) AS INVDRW_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS INVDRW_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT LEV_IND) AS INVDRW_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS INVDRW_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT FORMAT) AS INVDRW_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_SUBTYPE) AS INVDRW_CAX_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_VAR_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_VAR IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_VAR_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_VAR IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_VAR) AS INVDRW_CAX_VAR_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_DOC_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT DOC_NAME_ENG) AS INVDRW_DOC_NAME_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_DISC_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_DISC_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_FIL_DISC) AS INVDRW_CAX_FIL_DISC_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_PATH_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_PATH_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_FIL_PATH) AS INVDRW_CAX_FIL_PATH_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LOCAL_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_LOCAL IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_LOCAL_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_LOCAL IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_LOCAL) AS INVDRW_CAX_LOCAL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FIL_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_FIL_NAME) AS INVDRW_CAX_FIL_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_STROK_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STROK IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CAX_STROK_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STROK IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_STROK) AS INVDRW_CAX_STROK_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_SURF_FIN_NULL_CNT
FROM T_DOC_INVDRW
WHERE SURF_FIN IS NULL;

SELECT COUNT(C_ID) AS INVDRW_SURF_FIN_FILL_CNT
FROM T_DOC_INVDRW
WHERE SURF_FIN IS NOT NULL;

SELECT COUNT (DISTINCT SURF_FIN) AS INVDRW_SURF_FIN_CARD
FROM T_DOC_INVDRW;

SELECT COUNT(C_ID) AS INVDRW_SCALE_NULL_CNT
FROM T_DOC_INVDRW
WHERE SCALE IS NULL;

SELECT COUNT(C_ID) AS INVDRW_SCALE_FILL_CNT
FROM T_DOC_INVDRW
WHERE SCALE IS NOT NULL;

SELECT COUNT (DISTINCT SCALE) AS INVDRW_SCALE_CARD
FROM T_DOC_INVDRW;

SELECT COUNT(C_ID) AS INVDRW_COMP_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_COMP_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_COMP_MAP) AS INVDRW_CAX_COMP_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FRAME_ID_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_FRAME_ID_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_FRAME_ID) AS INVDRW_CAX_FRAME_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_STD_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_STD_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_STD_MAP) AS INVDRW_CAX_STD_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT EDB_URL) AS INVDRW_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CRE_SYSTEM_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_CRE_SYSTEM_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS INVDRW_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT VAL_FROM) AS INVDRW_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT(C_ID) AS INVDRW_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'INVDRW';

SELECT COUNT (DISTINCT VAL_UNTIL) AS INVDRW_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'INVDRW';