/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS ACAD_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_OPBH_NULL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.opbh IS NULL AND T_DOC_DAT.DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_OPBH_FILL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.opbh IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_SCALE_NULL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.scale IS NULL AND T_DOC_DAT.DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_SCALE_FILL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.scale IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_COMP_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_COMP_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_STEP_DESCR_NULL_CNT
FROM T_DOC_DAT
WHERE STEP_DESCR IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_STEP_DESCR_FILL_CNT
FROM T_DOC_DAT
WHERE STEP_DESCR IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_SCALE_TXT_NULL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.scale_txt IS NULL AND T_DOC_DAT.DOC_TYPE = 'ACAD';

SELECT COUNT(T_DOC_DAT.C_ID) AS ACAD_SCALE_TXT_FILL_CNT
FROM T_DOC_DAT, T_DOC_ACAD
WHERE 
T_DOC_DAT.C_ID = T_DOC_ACAD.C_ID 
AND t_doc_acad.scale_txt IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FRAME_ID_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_FRAME_ID_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_STD_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_STD_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NOT NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_01_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NULL AND DOC_TYPE = 'ACAD';

SELECT COUNT(C_ID) AS ACAD_CAX_01_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NOT NULL AND DOC_TYPE = 'ACAD';