/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (AutoCAD Vewfiles) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS GAMVIEW_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS GAMVIEW_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT DOC_VERSION) AS GAMVIEW_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT SHEET_NO) AS GAMVIEW_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT TNBL) AS GAMVIEW_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS GAMVIEW_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS GAMVIEW_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT FREE_NAME) AS GAMVIEW_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS GAMVIEW_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT DOC_TYPE) AS GAMVIEW_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PMT_REF_NO) AS GAMVIEW_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PLANT_ID) AS GAMVIEW_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT LOC_ID) AS GAMVIEW_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS GAMVIEW_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT LEV_IND) AS GAMVIEW_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS GAMVIEW_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT FORMAT) AS GAMVIEW_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_DOC_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT DOC_NAME_ENG) AS GAMVIEW_DOC_NAME_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_OPBH_NULL_CNT
FROM T_DOC_GAMVIEW
WHERE
OPBH IS NULL;

SELECT COUNT(C_ID) AS GAMVIEW_OPBH_FILL_CNT
FROM T_DOC_GAMVIEW
WHERE
OPBH IS NOT NULL;

SELECT COUNT (DISTINCT OPBH) AS GAMVIEW_OPBH_CARD
FROM T_DOC_GAMVIEW;

SELECT COUNT(C_ID) AS GAMVIEW_SCALE_NULL_CNT
FROM T_DOC_GAMVIEW
WHERE
SCALE IS NULL;

SELECT COUNT(C_ID) AS GAMVIEW_SCALE_FILL_CNT
FROM T_DOC_GAMVIEW
WHERE
SCALE IS NOT NULL;

SELECT COUNT (DISTINCT SCALE) AS GAMVIEW_SCALE_CARD
FROM T_DOC_GAMVIEW;

SELECT COUNT(C_ID) AS GAMVIEW_EDB_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_EDB_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT EDB_URL) AS GAMVIEW_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_CRE_SYSTEM_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_CRE_SYSTEM_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS GAMVIEW_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT VAL_FROM) AS GAMVIEW_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT(C_ID) AS GAMVIEW_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'GAMVIEW';

SELECT COUNT (DISTINCT VAL_UNTIL) AS GAMVIEW_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'GAMVIEW';