/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (Software Documents) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS SOF_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS SOF_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT DOC_VERSION) AS SOF_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT SHEET_NO) AS SOF_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT TNBL) AS SOF_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS SOF_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS SOF_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT FREE_NAME) AS SOF_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS SOF_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT DOC_TYPE) AS SOF_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_TYPE_NULL_CNT
FROM T_DOC_SOF
WHERE TYPE IS NULL;

SELECT COUNT(C_ID) AS SOF_TYPE_FILL_CNT
FROM T_DOC_SOF
WHERE TYPE IS NOT NULL;

SELECT COUNT (DISTINCT TYPE) AS SOF_TYPE_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_REF_NO) AS SOF_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_REF_NOREV_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO_REV IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_REF_NOREV_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO_REV IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_REF_NO_REV) AS SOF_PMT_REF_NO_REV_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT CAX_TYPE) AS SOF_CAX_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PLANT_ID) AS SOF_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT LOC_ID) AS SOF_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS SOF_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT LEV_IND) AS SOF_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS SOF_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT FORMAT) AS SOF_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_ORDERNO_NULL_CNT
FROM T_DOC_SOF
WHERE ORDERNO IS NULL;

SELECT COUNT(C_ID) AS SOF_ORDERNO_FILL_CNT
FROM T_DOC_SOF
WHERE ORDERNO IS NOT NULL;

SELECT COUNT (DISTINCT ORDERNO) AS SOF_ORDERNO_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_CUSTOMER_NULL_CNT
FROM T_DOC_SOF
WHERE CUSTOMER IS NULL;

SELECT COUNT(C_ID) AS SOF_CUSTOMER_FILL_CNT
FROM T_DOC_SOF
WHERE CUSTOMER IS NOT NULL;

SELECT COUNT (DISTINCT CUSTOMER) AS SOF_CUSTOMER_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_CUSTOMNR_NULL_CNT
FROM T_DOC_SOF
WHERE CUSTOMNR IS NULL;

SELECT COUNT(C_ID) AS SOF_CUSTOMNR_FILL_CNT
FROM T_DOC_SOF
WHERE CUSTOMNR IS NOT NULL;

SELECT COUNT (DISTINCT CUSTOMNR) AS SOF_CUSTOMNR_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_COUNTRY_NULL_CNT
FROM T_DOC_SOF
WHERE COUNTRY IS NULL;

SELECT COUNT(C_ID) AS SOF_COUNTRY_FILL_CNT
FROM T_DOC_SOF
WHERE COUNTRY IS NOT NULL;

SELECT COUNT (DISTINCT COUNTRY) AS SOF_COUNTRY_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_SERIAL_NO_ID_NULL_CNT
FROM T_DOC_SOF
WHERE SERIAL_NO_ID IS NULL;

SELECT COUNT(C_ID) AS SOF_SERIAL_NO_ID_FILL_CNT
FROM T_DOC_SOF
WHERE SERIAL_NO_ID IS NOT NULL;

SELECT COUNT (DISTINCT SERIAL_NO_ID) AS SOF_SERIAL_NO_ID_CARD
FROM T_DOC_SOF;

SELECT COUNT(C_ID) AS SOF_EDB_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_EDB_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT EDB_URL) AS SOF_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT VAL_FROM) AS SOF_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'SOF';

SELECT COUNT(C_ID) AS SOF_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'SOF';

SELECT COUNT (DISTINCT VAL_UNTIL) AS SOF_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SOF';