/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (Pro/E Drawings) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS PROED_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS PROE_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT DOC_VERSION) AS PROE_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT SHEET_NO) AS PROE_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT TNBL) AS PROE_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS PROE_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS PROE_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT FREE_NAME) AS PROE_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS PROE_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT DOC_TYPE) AS PROE_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_TYPE) AS PROE_CAX_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT DOC_SUBTYPE) AS PROE_DOC_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PMT_REF_NO) AS PROE_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PLANT_ID) AS PROE_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT LOC_ID) AS PROE_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS PROE_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT LEV_IND) AS PROE_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS PROE_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT FORMAT) AS PROE_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_SUBTYPE) AS PROE_CAX_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_VAR_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_VAR IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_VAR_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_VAR IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_VAR) AS PROE_CAX_VAR_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_DOC_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT DOC_NAME_ENG) AS PROE_DOC_NAME_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_DISC_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_DISC_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_FIL_DISC) AS PROE_CAX_FIL_DISC_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_PATH_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_PATH_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_FIL_PATH) AS PROE_CAX_FIL_PATH_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LOCAL_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_LOCAL IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_LOCAL_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_LOCAL IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_LOCAL) AS PROE_CAX_LOCAL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_FIL_NAME) AS PROE_CAX_FIL_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_EXT_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_03 IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FIL_EXT_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_03 IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_03) AS PROE_FIL_EXT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_STROK_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STROK IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CAX_STROK_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STROK IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_STROK) AS PROE_CAX_STROK_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_OPBH_NULL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.OPBH IS NULL;

SELECT COUNT(C_ID) AS PROED_OPBH_FILL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.OPBH IS NOT NULL;

SELECT COUNT (DISTINCT OPBH) AS PROE_OPBH_CARD
FROM T_DOC_PROED;

SELECT COUNT(C_ID) AS PROED_SCALE_NULL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.SCALE IS NULL;

SELECT COUNT(C_ID) AS PROED_SCALE_FILL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.SCALE IS NOT NULL;

SELECT COUNT (DISTINCT SCALE) AS PROE_SCALE_CARD
FROM T_DOC_PROED;

SELECT COUNT(C_ID) AS PROED_ECP_X_NULL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_X IS NULL;

SELECT COUNT(C_ID) AS PROED_ECP_X_FILL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_X IS NOT NULL;

SELECT COUNT (DISTINCT ECP_X) AS PROE_ECP_X_CARD
FROM T_DOC_PROED;

SELECT COUNT(C_ID) AS PROED_ECP_Y_NULL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_Y IS NULL;

SELECT COUNT(C_ID) AS PROED_ECP_Y_FILL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_Y IS NOT NULL;

SELECT COUNT (DISTINCT ECP_Y) AS PROE_ECP_Y_CARD
FROM T_DOC_PROED;

SELECT COUNT(C_ID) AS PROED_ECP_Z_NULL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_Z IS NULL;

SELECT COUNT(C_ID) AS PROED_ECP_Z_FILL_CNT
FROM T_DOC_PROED
WHERE 
t_doc_PROED.ECP_Z IS NOT NULL;

SELECT COUNT (DISTINCT ECP_Z) AS PROE_ECP_Z_CARD
FROM T_DOC_PROED;

SELECT COUNT(C_ID) AS PROED_COMP_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_COMP_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_COMP_MAP) AS PROE_CAX_COMP_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FRAME_ID_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_FRAME_ID_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_FRAME_ID) AS PROE_CAX_FRAME_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_STD_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_STD_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_STD_MAP) AS PROE_CAX_STD_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT EDB_URL) AS PROE_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CRE_SYSTEM_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_CRE_SYSTEM_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS PROE_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT VAL_FROM) AS PROE_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'PROED';

SELECT COUNT(C_ID) AS PROED_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'PROED';

SELECT COUNT (DISTINCT VAL_UNTIL) AS PROE_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'PROED';