/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (SolidWorks Drawings) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS SLDDRW_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS SLDDRW_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT DOC_VERSION) AS SLDDRW_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT SHEET_NO) AS SLDDRW_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT TNBL) AS SLDDRW_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS SLDDRW_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS SLDDRW_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT FREE_NAME) AS SLDDRW_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS SLDDRW_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT DOC_TYPE) AS SLDDRW_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_TYPE IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_TYPE) AS SLDDRW_CAX_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT DOC_SUBTYPE) AS SLDDRW_DOC_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PMT_REF_NO) AS SLDDRW_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PLANT_ID) AS SLDDRW_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT LOC_ID) AS SLDDRW_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS SLDDRW_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT LEV_IND) AS SLDDRW_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CHK_BY_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_PMT_CHK_BY_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CHK_BY IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT PMT_CHK_BY) AS SLDDRW_PMT_CHK_BY_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT FORMAT) AS SLDDRW_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_DOC_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT DOC_NAME_ENG) AS SLDDRW_DOC_NAME_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_SUBTYPE IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_SUBTYPE) AS SLDDRW_CAX_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_DISC_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_DISC_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_DISC IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_FIL_DISC) AS SLDDRW_CAX_FIL_DISC_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_PATH_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_PATH_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_PATH IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_FIL_PATH) AS SLDDRW_CAX_FIL_PATH_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FIL_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FIL_NAME IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_FIL_NAME) AS SLDDRW_CAX_FIL_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_RAW_ID_NULL_CNT
FROM T_DOC_DAT
WHERE RAW_ID IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_RAW_ID_FILL_CNT
FROM T_DOC_DAT
WHERE RAW_ID IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT RAW_ID) AS SLDDRW_RAW_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_04_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_04 IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_04_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_04 IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_04) AS SLDDRW_CAX_04_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_02_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_02 IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_02_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_02 IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_02) AS SLDDRW_CAX_02_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_MATERIAL_NULL_CNT
FROM T_DOC_DAT
WHERE MATERIAL IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_MATERIAL_FILL_CNT
FROM T_DOC_DAT
WHERE MATERIAL IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT MATERIAL) AS SLDDRW_MATERIAL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_MAT_AISI_NULL_CNT
FROM T_DOC_DAT
WHERE MAT_AISI IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_MAT_AISI_FILL_CNT
FROM T_DOC_DAT
WHERE MAT_AISI IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT MAT_AISI) AS SLDDRW_MAT_AISI_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_WIDTH_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE WIDTH IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_WIDTH_FILL_CNT 
FROM T_DOC_SLDDRW 
WHERE WIDTH IS NOT NULL;

SELECT COUNT (DISTINCT WIDTH) AS SLDDRW_WIDTH_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_LENGTH_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE LENGTH IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_LENGTH_FILL_CNT 
FROM T_DOC_SLDDRW 
WHERE LENGTH IS NOT NULL;

SELECT COUNT (DISTINCT LENGTH) AS SLDDRW_LENGTH_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_HEIGHT_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE HEIGHT IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_HEIGHT_FILL_CNT 
FROM T_DOC_SLDDRW 
WHERE HEIGHT IS NOT NULL;

SELECT COUNT (DISTINCT HEIGHT) AS SLDDRW_HEIGHT_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_CAX_01_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CAX_01_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_01 IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_01) AS SLDDRW_CAX_01_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CUT_LOUT_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE CUT_LENG_OUT IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_CUT_LOUT_FILL_CNT 
FROM T_DOC_SLDDRW 
WHERE CUT_LENG_OUT IS NOT NULL;

SELECT COUNT (DISTINCT CUT_LENG_OUT) AS SLDDRW_CUT_LOUT_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_CUT_LIN_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE CUT_LENG_IN IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_CUT_LIN_FILL_CNT 
FROM T_DOC_SLDDRW 
WHERE CUT_LENG_IN IS NOT NULL;

SELECT COUNT (DISTINCT CUT_LENG_IN) AS SLDDRW_CUT_LIN_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_BENDS_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE BENDS IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_BENDS_FILL_CNT
FROM T_DOC_SLDDRW 
WHERE BENDS IS NOT NULL;

SELECT COUNT (DISTINCT BENDS) AS SLDDRW_BENDS_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_SURF_FIN_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE SURF_FIN IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_SURF_FIN_FILL_CNT
FROM T_DOC_SLDDRW 
WHERE SURF_FIN IS NOT NULL;

SELECT COUNT (DISTINCT SURF_FIN) AS SLDDRW_SURF_FIN_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_SCALE_NULL_CNT
FROM T_DOC_SLDDRW
WHERE SCALE IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_SCALE_FILL_CNT
FROM T_DOC_SLDDRW
WHERE SCALE IS NOT NULL;

SELECT COUNT (DISTINCT SCALE) AS SLDDRW_SCALE_CARD
FROM T_DOC_SLDDRW;

SELECT COUNT(C_ID) AS SLDDRW_COMP_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_COMP_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_COMP_MAP IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_COMP_MAP) AS SLDDRW_CAX_COMP_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FRAME_ID_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_FRAME_ID_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_FRAME_ID IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_FRAME_ID) AS SLDDRW_CAX_FRAME_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_STD_MAP_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_STD_MAP_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_STD_MAP IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_STD_MAP) AS SLDDRW_CAX_STD_MAP_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_URL_NULL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_URL_FILL_CNT
FROM T_DOC_DAT
WHERE EDB_URL IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT EDB_URL) AS SLDDRW_EDB_URL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CRE_SYSTEM_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_CRE_SYSTEM_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS SLDDRW_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT VAL_FROM) AS SLDDRW_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'SLDDRW';

SELECT COUNT (DISTINCT VAL_UNTIL) AS SLDDRW_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SLDDRW';

SELECT COUNT(C_ID) AS SLDDRW_OPBH_NULL_CNT 
FROM T_DOC_SLDDRW 
WHERE OPBH IS NULL;

SELECT COUNT(C_ID) AS SLDDRW_OPBH_FILL_CNT
FROM T_DOC_SLDDRW 
WHERE OPBH IS NOT NULL;

SELECT COUNT (DISTINCT OPBH) AS SLDDRW_OPBH_CARD
FROM T_DOC_SLDDRW;