/*  Written by:   Jesco Wurm (ICP)
    Date:         03-01-2025
    Function:     Measuring and evaluation of field data for DPH (SCAN) 
                  APPPLM-3443: As a DPH user, we would like to prepare the list of fields of each E6 document type tp be sent to DPH 
*/
SELECT COUNT(C_ID) AS SCAN_DOCID_NULL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOCID_FILL_CNT
FROM T_DOC_DAT
WHERE DOCUMENT_ID IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT DOCUMENT_ID) AS SCAN_DOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_VERSION_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_VERSION_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_VERSION IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT DOC_VERSION) AS SCAN_DOC_VERSION_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_SHEET_NO_NULL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_SHEET_NO_FILL_CNT
FROM T_DOC_DAT
WHERE SHEET_NO IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT SHEET_NO) AS SCAN_SHEET_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_TNBL_NULL_COUNT
FROM T_DOC_DAT
WHERE TNBL IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_TNBL_FILL_CNT
FROM T_DOC_DAT
WHERE TNBL IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT TNBL) AS SCAN_TNBL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_CRE_USER_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_CRE_USER_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_USER IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT PMT_CRE_USER) AS SCAN_PMT_CRE_USER_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_STBN_ENG_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_STBN_ENG_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_STBN_ENG IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT PMT_STBN_ENG) AS SCAN_PMT_STBN_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_FREE_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_FREE_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE FREE_NAME IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT FREE_NAME) AS SCAN_FREE_NAME_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_CRE_DATE_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_CRE_DATE_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_CRE_DATE IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT PMT_CRE_DATE) AS SCAN_PMT_CRE_DATE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_TYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_TYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_TYPE IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT DOC_TYPE) AS SCAN_DOC_TYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_SUBTYPE_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_SUBTYPE_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_SUBTYPE IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT DOC_SUBTYPE) AS SCAN_DOC_SUBTYPE_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_REF_NO_NULL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PMT_REF_NO_FILL_CNT
FROM T_DOC_DAT
WHERE PMT_REF_NO IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT PMT_REF_NO) AS SCAN_PMT_REF_NO_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PLANT_ID_NULL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_PLANT_ID_FILL_CNT
FROM T_DOC_DAT
WHERE PLANT_ID IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT PLANT_ID) AS SCAN_PLANT_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_LOC_ID_NULL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_LOC_ID_FILL_CNT
FROM T_DOC_DAT
WHERE LOC_ID IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT LOC_ID) AS SCAN_LOC_ID_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_SFS_CAX_DIM_NULL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_SFS_CAX_DIM_FILL_CNT
FROM T_DOC_DAT
WHERE SFS_CAX_DIM IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT SFS_CAX_DIM) AS SCAN_SFS_CAX_DIM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_LEV_IND_NULL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_LEV_IND_FILL_CNT
FROM T_DOC_DAT
WHERE LEV_IND IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT LEV_IND) AS SCAN_LEV_IND_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_FORMAT_NULL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_FORMAT_FILL_CNT
FROM T_DOC_DAT
WHERE FORMAT IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT FORMAT) AS SCAN_FORMAT_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_NAME_NULL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_DOC_NAME_FILL_CNT
FROM T_DOC_DAT
WHERE DOC_NAME_ENG IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT DOC_NAME_ENG) AS SCAN_DOC_NAME_ENG_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_OPBH_NULL_CNT
FROM PMT_DOC_SCAN
WHERE
OPBH IS NULL;

SELECT COUNT(C_ID) AS SCAN_OPBH_FILL_CNT
FROM PMT_DOC_SCAN
WHERE
OPBH IS NOT NULL;

SELECT COUNT (DISTINCT OPBH) AS SCAN_OPBH_CARD
FROM PMT_DOC_SCAN;

SELECT COUNT(C_ID) AS SCAN_CRE_SYSTEM_NULL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_CRE_SYSTEM_FILL_CNT
FROM T_DOC_DAT
WHERE CAX_CRE_SYSTEM IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT CAX_CRE_SYSTEM) AS SCAN_CAX_CRE_SYSTEM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_VAL_FROM_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_VAL_FROM_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_FROM IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT VAL_FROM) AS SCAN_VAL_FROM_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_VAL_UNTIL_NULL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT(C_ID) AS SCAN_VAL_UNTIL_FILL_CNT
FROM T_DOC_DAT
WHERE VAL_UNTIL IS NOT NULL AND DOC_TYPE = 'SCAN';

SELECT COUNT (DISTINCT VAL_UNTIL) AS SCAN_VAL_UNTIL_CARD
FROM T_DOC_DAT
WHERE DOC_TYPE = 'SCAN';