CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_PLM_DPH_ITEM" 
  ("ECO_NUMBER", "ECO_ITM_INTGR_JOB_STATUS", "ECO_ITM_INTGR_JOB_ERR_MESS", 
   "PART_ID", "PART_VERSION", "PMT_STB_ENG", "FREE_NAME", "ART_TYP", "PART_SUBTYPE", 
   "MATERIAL", "UNIT", "FCM", "NORM_TYPE", "SUPPLIER", "DIC_BRAND", "ORDER_DATA", 
   "ADDITIONAL_INFO", "AE_CODE_STATUS", "EDB_ID", "ITEM_PREVIEW", "ORG_FILE_NAME", 
   "SPARE", "SAP_ITEM_TYPE", "PLM_PLANT_ID", "LOC_ID", "OBSOLETE", 
   "REPLACED_BY_ITEM_NR", "AUTR", "ADTE", "VAL_FROM", "ITEM_COMMENT", "SERVICE", 
   "SERV_BOM", "REF_NO", "QLEVEL")
DEFAULT COLLATION "USING_NLS_COMP"  
AS 
WITH 
  /* Original  CTE commented out for APPPLM-3607
  28.02.2025 Jesco Wurm (ICP)
  AE_CODE AS (
    SELECT CASE WHEN COUNT(AE_ITM.C_ID) > 1 THEN 1 ELSE 0 END "AE_CODE_STATUS", 
           AE_ITM.C_ID 
    FROM T_MASTER_STR, T_MASTER_DAT AE_ITM
    WHERE T_MASTER_STR.C_ID_2 = AE_ITM.C_ID 
      AND (T_MASTER_STR.SEIM IS NOT NULL 
        OR T_MASTER_STR.SEIM_1 IS NOT NULL 
        OR T_MASTER_STR.SFS_IDSERVICE IS NOT NULL)
    GROUP BY AE_ITM.C_ID
  )
  */
  -- New version APPPLM-3607 28.02.2025 Jesco Wurm (ICP)
  AE_CODE AS (
    SELECT AE_ITM.C_ID,
           CASE 
             WHEN EXISTS (
               SELECT 1 
               FROM T_MASTER_STR 
               WHERE T_MASTER_STR.C_ID_2 = AE_ITM.C_ID 
                 AND (T_MASTER_STR.SEIM IS NOT NULL 
                      OR T_MASTER_STR.SEIM_1 IS NOT NULL 
                      OR T_MASTER_STR.SFS_IDSERVICE IS NOT NULL)
             ) THEN 1 
             ELSE 0 
           END AS AE_CODE_STATUS
    FROM T_MASTER_DAT AE_ITM
  )
  -- End of change for APPPLM-3607
SELECT 
    ECO_ITM.ECO_NUMBER,
    ECO_ITM.ECO_ITM_INTGR_JOB_STATUS,
    ECO_ITM.ECO_ITM_INTGR_JOB_ERR_MESS,
    ECO_ITM.ITEM_NUMBER AS "PART_ID",
    ECO_ITM.REVISION AS "PART_VERSION",
    UPPER(ECO_ITM.PMT_STB_ENG) AS PMT_STB_ENG, -- reintroduced with APPPLM-2909
    ECO_ITM.FREE_NAME,
    ECO_ITM.PLM_ITEM_TYPE AS "ART_TYP",
    ECO_ITM.PLM_ITEM_SUBTYPE AS "PART_SUBTYPE",
    ITEM.MATERIAL,
    ECO_ITM.UNIT_OF_MEASURE AS "UNIT",
    ECO_ITM.FCM,
    ITEM.NORM_TYPE,
    ITEM.SUPPLIER,
    ITEM.DIC_BRAND,
    ITEM.ORDER_DATA,
    ITEM.ADDITIONAL_INFO,
    NVL(AE_CODE.AE_CODE_STATUS, 0) AS AE_CODE_STATUS,
    ITEM.EDB_ID,
    ITEM.ART_BLOB AS "ITEM_PREVIEW",
    REGEXP_REPLACE(
      (ITEM.PART_ID || '_' || ITEM.PART_VERSION || '_1' ||
         CASE 
           WHEN utl_raw.cast_to_varchar2(dbms_lob.substr(ITEM.ART_BLOB)) LIKE '%IHDR%' THEN '.png'
           WHEN utl_raw.cast_to_varchar2(dbms_lob.substr(ITEM.ART_BLOB)) LIKE '%JFIF%' THEN '.jpg'
           WHEN utl_raw.cast_to_varchar2(dbms_lob.substr(ITEM.ART_BLOB)) LIKE '%GIF%'  THEN '.gif'
           ELSE '.unknown'
         END),
      '.*unknown.*', ''
    ) AS org_file_name, --APPPLM-2459
    ECO_ITM.PLM_ITEM_SPARE AS SPARE, --APPPLM-2415
    ECO_ITM.SAP_ITEM_TYPE,
    ECO_ITM.PLM_PLANT_ID,
    ECO_ITM.LOC_ID,
    ECO_ITM.OBSOLETE,
    ECO_ITM.REPLACED_BY_ITEM_NR,
    ITEM.AUTR AS "AUTR", --APPPLM-2403
    ITEM.ADTE AS "ADTE", --APPPLM-2403
    ITEM.VAL_FROM AS "VAL_FROM", --APPPLM-2403
    ECO_ITM.ITEM_COMMENT, --APPPLM-2682
    ITEM.SERVICE AS "SERVICE", --APPPLM-3305
    ITEM.SFS_SERV_BOM AS "SERV_BOM", --APPPLM-3305
    ITEM.BINR AS "REF_NO", --APPPLM-3339
    ECO_ITM.QLEVEL AS "QLEVEL" --APPPLM-3339
FROM T_ERP_ECO_ITM ECO_ITM
LEFT JOIN T_MASTER_DAT ITEM 
    ON ECO_ITM.ITEM_NUMBER = ITEM.PART_ID 
   AND NVL(ECO_ITM.REVISION, '-') = NVL(ITEM.PART_VERSION, '-')
LEFT JOIN AE_CODE 
    ON AE_CODE.C_ID = ITEM.C_ID;
